create table if not exists public.recipes (
    recipe_id text primary key,
    title text not null,
    category text not null,
    url text,
    star_rating double precision,
    review_count integer,
    ingredients jsonb not null default '[]'::jsonb,
    steps jsonb not null default '[]'::jsonb,
    descriptors jsonb not null default '[]'::jsonb,
    descriptor_count integer not null default 0,
    descriptor_code_counts jsonb not null default '{}'::jsonb,
    chatbot_context text not null,
    chunks jsonb not null default '[]'::jsonb,
    version_2_ingredients jsonb not null default '[]'::jsonb,
    version_2_steps jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

alter table public.recipes
    add column if not exists version_2_ingredients jsonb not null default '[]'::jsonb;

alter table public.recipes
    add column if not exists version_2_steps jsonb not null default '[]'::jsonb;

create table if not exists public.recipe_chunks (
    chunk_id text primary key,
    recipe_id text not null references public.recipes(recipe_id) on delete cascade,
    title text not null,
    text text not null,
    text_hash text not null,
    embedding_model text not null,
    embedding jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.feedback_events (
    event_id bigint generated by default as identity primary key,
    timestamp timestamptz not null,
    session_id text not null,
    recipe_id text not null references public.recipes(recipe_id) on delete cascade,
    panel_id text not null,
    content_version text not null,
    app_version text not null,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_recipes_category on public.recipes(category);
create index if not exists idx_recipe_chunks_recipe_id on public.recipe_chunks(recipe_id);
create index if not exists idx_feedback_events_recipe_id on public.feedback_events(recipe_id);
create index if not exists idx_feedback_events_timestamp on public.feedback_events(timestamp desc);
